// agent-loop-workflow — Host half
// Registers the multi-agent collaboration workflow as a dynamic skill.
// Install: dsh plugin --profile web add "github:LeslieWylie/agent-loop-workflow"
module.exports = {
  inject: ['skills'],
  apply(ctx) {
    const skills = ctx.get('skills')
    if (skills === undefined) return

    skills.register({
      name: 'agent-loop-workflow',
      description: '项目无关的多 agent 协作工作流骨架——收到任务→执行→交接/评审→收口的通用契约。适用于任何用 Octo/octo-daemon 编排的 DRI+review+lead+运维 小队：Loop Guard 循环防护六不变量、标准 handoff 格式、风险三档分流(fast/standard/high)、交付顺序与 in_review 交接协议、完成判定。',
      whenToUse: '当 agent 需要知道"怎么在一个多角色 loop 里正确协作、何时升级、何时收口"时加载本 skill',
      source: 'runtime',
      content: [
        '---',
        'name: agent-loop-workflow',
        'description: 项目无关的多 agent 协作工作流骨架——收到任务→执行→交接/评审→收口的通用契约',
        '---',
        '',
        '# agent-loop-workflow — 通用多 agent 协作工作流骨架',
        '',
        '本 skill 是**项目无关**的协作契约。任何 DRI + review + lead + 运维组成的 Octo 小队都能 load 它拿到统一的工作流规则，不必在每个 agent 的 instructions 里各抄一份。',
        '',
        '**边界**：本 skill 只讲"怎么协作、何时升级、何时收口"这类**流程骨架**。具体项目的**领域知识**（代码集成坑、评审检查清单、仓库路径、模型配置）不放这里——放在各项目自己的 `*-conventions` / `*-engineering` / `*-review-rules` skill 里。',
        '',
        '---',
        '',
        '## 1. 角色拓扑（通用四类）',
        '',
        '| 角色 | 职责 | 不做 |',
        '|---|---|---|',
        '| **DRI**（默认执行者） | 收到实现/调试/实验任务直接推进，不等确认 | 高价值架构决策、自派 reviewer |',
        '| **reviewer**（评审） | 收到 review 请求按规则评审、写结论 metadata | 自行改 status、自行 merge |',
        '| **lead**（决策/路由） | 只在架构决策/验收不清/reviewer 冲突/triage 拆解时介入 | 替 DRI 写码、替 reviewer 审批、机械收口 |',
        '| **运维**（自动化） | watchdog/staleness/状态同步等幂等自动化任务 | 做 DRI、机械操作、改业务 status/assignee |',
        '',
        '---',
        '',
        '## 2. Loop Guard 循环防护（所有执行型 agent 遵守）',
        '',
        '1. **轮次**：单次 task 工具调用轮次参考上限 20 轮，接近时运维预警，留给 agent 自己判断收口。',
        '2. **无进展**：连续多轮（参考：3 轮）看不到有效进展时，agent 应该主动评估是否卡住了。',
        '3. **同错**：同一错误（归一化签名）反复出现（参考：3 次）时判断是否换个思路。',
        '4. **耗时**：单次运行明显偏离任务量级该有的时长（参考：120 分钟）时自我评估是否该收口。',
        '5. **显式退出门**：完成判定 = 退出协议已执行 AND verification.json all_passed AND verified_commit == HEAD。',
        '6. **单一权威写入**：loop-state.json 由运维 agent 单一权威写入，其他 agent 只能通过 issue 评论请求更新。',
        '',
        '---',
        '',
        '## 3. 标准 handoff 格式（任务交接/升级时用）',
        '',
        '```',
        '负责人：',
        '目标：',
        '输入与资源 ID：',
        '允许的写操作：',
        '验收标准：',
        '失败时需要回报的证据：',
        '```',
        '---',
        '',
        '## 4. 风险三档分流',
        '',
        '| lane | 判据 | reviewer |',
        '|---|---|---|',
        '| **fast** | 纯文档/CI/配置/小 bug，不碰核心 | 仅工程 reviewer |',
        '| **standard** | 多文件/接口变化，不碰核心算法 | 仅工程 reviewer |',
        '| **high** | 命中核心算法路径，或涉及 reward/归一化/采样/去重/hash 等语义变化 | 工程 + 算法 reviewer |',
        '',
        '---',
        '',
        '## 5. 交付顺序（DRI 固定流程，不可打乱）',
        '',
        '```',
        '验证 → commit → push 分支 → 创建 Draft MR → 写 pr_url metadata',
        '→ 在 GitLab MR 评论区发 /ready → 发结果评论到 issue → 置 in_review',
        '```',
        '',
        '关键约束：',
        '- 分支名/MR 标题必须带 issue key',
        '- 分支干净：只含本任务改动',
        '- /ready 必须发到 GitLab MR 评论区',
        '- in_review 必须是本 task 最后一个写操作',
        '- 每轮打回改完后重走验证→push→/ready',
        '- non-fast-forward 时停止复核，严禁 force-push',
        '',
        '---',
        '',
        '## 6. review → 收口协议',
        '',
        '- in_review 是唯一的自动 review 交接信号',
        '- reviewer 出结论写 metadata，不自行改 status',
        '- 通过 → 置 done；打回 → 改回 DRI + 置 todo|in_progress',
        '- 打回来回几轮后如果还没收敛，判断是否该升级引入更高 lane 的 reviewer',
        '',
        '---',
        '',
        '## 7. 防回环',
        '',
        '- issue 状态变化消息是 webhook 自动推的，不是人类新需求',
        '- 只有人类明确 @/私聊的新需求才触发建单',
        '- 幂等：同一需求只建一个 issue',
        '',
        '---',
        '',
        '## 8. 通用红线',
        '',
        '- 密钥红线：任何 token / API key / bot token / webhook secret / 签名 URL 绝不进 issue 评论、聊天消息、日志',
        '- GitLab token 只读用途的角色严禁写操作',
        '- 调 GitLab API 不在 shell 里字面拼 token',
        '- 涉及真实算力、破坏性操作、跨人资源时先确认 owner',
        '',
        '---',
        '',
        '## 相关',
        '',
        '- 项目领域知识：见各项目自己的 `*-conventions` / `*-engineering` / `*-review-rules` skill',
        '- 多评委评审模式：`skills/collaboration-review`（独立打分 + Chair 聚合 + Critic 复核）',
      ].join('\n'),
    })
  },
}
